### ISSUE TITLE
Using domain http://localhost:3000 in development and undefined method 'host' for safe_domain? 

### ISSUE THREAD

**Issue by Backoo** [sdsdkkk/safe_redirect#13]
Hi, I'm trying to use your SafeRedirect gem and have these issues:
  
   
1. My Rails app in development mode runs at `http://localhost:3000`. I tried the settings
```
SafeRedirect.configure do |config|
  config.default_path = '/home'
  config.domain_whitelists = ['http://localhost:3000', 'localhost:3000', 'http://localhost:3000/', 'localhost:3000/']
end
```
but can not get the `safe_path` to work (it returns always the default path `/home`):
```
safe_path('http://localhost:3000/') # => /home
safe_path('http://localhost:3000/some_path') # => /home
safe_path('http://localhost/some_path') # => /home
safe_path('localhost:3000/some_path') # => /home
```
   
   
2. When I run `safe_domain?('https://github.com/sdsdkkk')` then I get the error
`undefined method 'host' for "https://github.com/sdsdkkk":String`

The error trace is:
```
safe_redirect (0.2.6) lib/safe_redirect/safe_redirect.rb:67:in `valid_uri?'
safe_redirect (0.2.6) lib/safe_redirect/safe_redirect.rb:5:in `safe_domain?'
```

What to make to solve these issues?

**Comment by Backoo** [comment]
I solved the issues this way:

1. Added `config.whitelist_local = true` to the SafeRedirect initializer:
```
SafeRedirect.configure do |config|
  config.default_path = '/'
  config.whitelist_local = true
  config.domain_whitelists = []
  config.log = Rails.env.development?
end
```

2. I had to run `safe_domain?(URI('https://github.com/sdsdkkk'))`
